### ISSUE TITLE
Lost Scroll Bar

### ISSUE THREAD

**Issue by Omnialias** [fresh2dev/AnyBox#10]
After updating to the latest version, I seem to have lost the scroll bar, making very long prompts un-usable. Attempted to use the `-ResizeMode` property but this just gave me a lot white space on the right. Any way to get the scroll bar back, or alternatively any way to format the window into two columns of prompts?

**Comment by dm3ll3n** [comment]
Hmm... I wonder if this is related to the fix implemented for  #8 (see `<RowDefinition Height="Auto" />`). I won't have time to investigate anytime soon, but I'll leave the issue open, and PRs are welcome. Also, I like the idea of adding columns to the grid layout. Maybe in the future.

**Comment by fresh2dev** [comment]
> or alternatively any way to format the window into two columns of prompts?

Track support for multiple prompt columns here: #17
