### ISSUE TITLE
Button to copy

### ISSUE THREAD

**Issue by szczemp** [fresh2dev/AnyBox#16]
Haw can I create button or sth else to copy variable value without closing anybox?

And there is bug with datagrid. After use searchbox I cant sort columns.

**Comment by fresh2dev** [comment]
1. you can use a buttons `-OnClick` parameter to provide a scriptblock to do anything when clicked.
2. I am able to repro the bug.

Please limit issues to one topic. Closing this to reopen an issue for the bug.
