### ISSUE TITLE
Resize

### ISSUE THREAD

**Issue by RBNoronha** [fresh2dev/AnyBox#19]
Even with parameter Norisize -ResizeMode NoResize and =
-NoResize when it exceeds the limit it increases by itself. know how to help me

![image](https://user-images.githubusercontent.com/91945458/172745184-2a1c7515-b357-4544-a961-1585a36dbfed.png)

**Comment by RBNoronha** [comment]
> Even with parameter Norisize -ResizeMode NoResize and = -NoResize when it exceeds the limit it increases by itself. know how to help me
> 
<a href="https://imgur.com/6vjOGyZ"><img src="https://i.imgur.com/6vjOGyZ.gif" title="source: imgur.com" /></a>

**Comment by fresh2dev** [comment]
Provide a value for `-MaxWidth` and the text will wrap as expected. e.g., `Show-AnyBox -MaxWidth 300 ...`
