### ISSUE TITLE
Double Click and Copy?

### ISSUE THREAD

**Issue by g-pearl** [fresh2dev/AnyBox#9]
When using the GridData is there a way to have expose a double click instead of having to select a item/row then click ok or another button? 

As for the copy I am using the "New-AnyBoxButton -Template 'CopyMessage'" command with gridData and I select an entry/row and select copy and a prompt display that "There is no message to copy."  Am I trying to use the template in a manner that it was not intended for?
--  I am wanting to copy the selection to clipboard.  If more then one property is selected include the property title in the copy.  I understand this may be difficult to perform.

Thanks for the updates

**Comment by dm3ll3n** [comment]
The `CopyMessage` template is meant to copy a message displayed to the user with the `-Message` parameter; it does not read the grid data. To copy grid data to the clipboard, I'd suggest using the keyboard shortcut `CTRL+C`. You could take a look at how the `CopyMessage` template works and use that as a guide to implement your own button with an `-OnClick` script that copies the selected grid data. PRs are welcome.
